### ISSUE TITLE
Changes in API

### ISSUE THREAD

**Issue by ajakubo1** [ajakubo1/CanvasMenu#13]
I'm opening an issue to consult the community about API I'm giving for my library and it's intuitiveness. Some things may be unintuitive, or maybe I should open some property to the outside which has been closed?

From what I know, @michalbe has something in mind regarding this matter.

I'm pretty much open-minded to any suggestion. So... Let me know what you need, I'll consider it.

**Comment by michalbe** [comment]
First of all, I think we need to introduce scoping. Creating separate global constructor for every component will cause mess in the code with more than just two components. So instead of:

``` javascript
var myMenu = new Menu({});
var button = new Button({});
```

I propose something more like:

``` javascript
var myMenu = new CM.Menu({});
var button = new CM.Button({});
```

or:

``` javascript
var myMenu = new Menu({});
var button = new Menu.Button({});
```

or even:

``` javascript
var myMenu = new Menu({});
// DOM like API, inspired by document.createElement()
var button = myMenu.createButton({});
```

**Comment by michalbe** [comment]
If we plan to suport more events that just click (like `onmouseover`, etc.), we can use `.on()` method instead of the `.clickHandler()` what's not very intuitive. This pattern is known from `jQuery`, `Angular`, `KO`, and countless number of frameworks, so it will be easy to use for new users of CanvasMenu.
So example from the first sample:

``` javascript
button.clickHandler(function () {
    alert("You've clicked me!");
});
```

will become:

``` javascript
button.on('click', function () {
    alert("You've clicked me!");
});
```

For now each element can have just one `clickHandler` listener, it would be nicer to have multiple of them, like `addEventListener` compared to `onclick`. I suggest we should introduce `this.events` object, where we'll stack those. So 

``` javascript
Button.prototype.clickHandler = function (handler) {
    this.onclick = handler;
};
```

can be expanded to look more/less like this:

``` javascript
Button.prototype.on = function (eventType, handler) {
    this.events[eventType].push(handler);
};
```

**Comment by michalbe** [comment]
Setting new menu as a listener to switch between menus is not very clear as well. I think setting a listener that will initiate the menu on fly will be more clear and self explanatory, without unneeded magic happening on the backstage.
So 

``` javascript
optionsButton.clickHandler(optionsMenu);
```

will became:

``` javascript
optionsButton.on('click', optionsMenu.init);
```

This will simplify events handling in the library's code, and give more explicit control to the end user.

**Comment by michalbe** [comment]
When we'll implement new elements, `appendButton` method won't have any more sense. Adding Switch component or Radio control using `appendButton` sound strange. I suggest to rename the method to simple `append`

**Comment by michalbe** [comment]
Using `redraw` in all possible places makes the library look heavy. How about removing this from the name of all the configurable variables?
So instead of:

``` javascript
var newGameButton = new Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    redrawInactiveColor: '#FFFF00',
    redrawFocusedColor: '#660033',
    redrawDownColor: '#FF0033',
    redrawUpColor: '#330033',
    redrawInactiveFont: '#111111',
    redrawDownFont: '#111111',
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

we'll have:

``` javascript
var newGameButton = new CM.Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    idleColor: '#FFFF00',
    hoverColor: '#660033',
    activeColor: '#FF0033',
    upColor: '#330033',
    idleFont: '#111111',
    downFont: '#111111',
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

I also don't like `inactive`, `focused`, `down` and `up` names. Maybe `idle`, `hover`, `active` (like in CSS) and (... something else for `up` but I have no idea what for now) sound better? And maybe instead of configuring font & color as two attributes, we can use the object? like this:

``` javascript
var newGameButton = new CM.Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    idle: {
        color: '#FFFF00',
        font: ' #111111'
    },
    hover: {
        color: '#FFFF00',
        font: ' #111111'
    },
    active: {
        color: '#FFFF00',
        font: ' #111111'
    },
    up: {
        color: '#FFFF00',
        font: ' #111111'
    },
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

Methods could be added in the same way:

``` javascript
    idle: {
        color: '#FFFF00',
        font: ' #111111',
        fn: new RedrawIdleButton() // fn, event, method, or even 'before' or 
                                   // 'after' will work as a name here
    },
```

**Comment by ajakubo1** [comment]
@michalbe, I have to say, everything you've written makes a lot of sense, thanks for your input. Now I have to consider a lot more things to implement, but I think it will be better with your suggestions. I'll try to divide all of your suggestions into tasks and implement them for v1.2.0 (before all of the button stuff). I'm waiting for further suggestions.

**Comment by ajakubo1** [comment]
I've just realized, that according to semver, it'll be version 2.0.0, not 1.2.0 ;).

**Comment by michalbe** [comment]
Glad you like it, and of course I would love to help with the changes.
